Check for PSR2 coding standards with PHP-CS-Fixer
podio-community/podio-php pull request #209
Opened 2021-09-04 12:42 UTC by lucasmichot

Check for PSR2 coding standards with PHP-CS-Fixer

2021-09-05 09:06 UTC, daniel-sc approved these changes
Thanks for the contribution @lucasmichot! This is a good step forward. 
If you have time to even support PSR-12, I'd like to include that, but if you don't have time for that, it is fine for me as well!

2021-09-05 09:10 UTC, lucasmichot commented on .php-cs-fixer.dist.php
> +    '@PSR2' => true,
Sure 👍

2021-09-05 09:12 UTC, lucasmichot commented
> Thanks for the contribution @lucasmichot! This is a good step forward.
> If you have time to even support PSR-12, I'd like to include that, but if you don't have time for that, it is fine for me as well!

Hey @daniel-sc , I have added an extra PSR-12 ruleset check. Feel free to review this PR again

2021-09-05 09:58 UTC, daniel-sc approved these changes
Perfect - thanks for the ultra fast updat!

2021-09-05 18:36 UTC, rafaelmb requested changes
Do we mention PSR-2 and 12 on our contribution guide? I think we should start in this PR.

Besides that, thank you lucas for the contribution!

2021-09-05 19:21 UTC, daniel-sc commented
> Do we mention PSR-2 and 12 on our contribution guide? I think we should start in this PR.

@rafaelmb as we require "All build checks are passing", this is basically given? Of course, one could go for a more explicit description - but this could as well be confusing/demotivating for people not familiar with PSR-2/12?

2021-09-05 19:22 UTC, rafaelmb commented
This is better

2021-09-05 19:27 UTC, rafaelmb approved these changes

2021-09-06 01:26 UTC, rafaelmb approved these changes
LGTM

2021-09-06 14:45 UTC, merged